freedom-tech-hq/main

code/cross-platform-packages/freedom-data-source-types/src/types/GetOrCreateSyncableStoreArgs.ts
code/cross-platform-packages/freedom-data-source-types/src/types/InMemoryDataSources.ts
code/cross-platform-packages/freedom-sync-types/src/types/SyncableId.ts
code/cross-platform-packages/freedom-syncable-store-types/src/internal/types/DefaultFolderStore.ts
code/cross-platform-packages/freedom-syncable-store-types/src/internal/types/DefaultMutableSyncableFolderAccessor.ts
code/cross-platform-packages/freedom-syncable-store-types/src/internal/types/DefaultMutableSyncableFolderAccessorBase.ts
code/cross-platform-packages/freedom-syncable-store-types/src/internal/types/__tests__/folders.test.ts
code/cross-platform-packages/freedom-syncable-store-types/src/internal/types/__tests__/hashes.test.ts
code/cross-platform-packages/freedom-syncable-store-types/src/types/DefaultSyncableStore.ts
code/cross-platform-packages/freedom-syncable-store-types/src/types/SyncableStore.ts
code/cross-platform-packages/freedom-syncable-store-types/src/types/__tests__/DefaultSyncableStore.test.ts
code/cross-platform-packages/freedom-syncable-store-types/src/types/in-memory-backing/InMemorySyncableStoreBacking.ts
code/cross-platform-packages/freedom-syncable-store-types/src/types/in-memory-backing/internal/consts/special-ids.ts
code/cross-platform-packages/freedom-syncable-store-types/src/utils/__tests__/createConflictFreeDocumentBundleAtPath.test.ts
code/cross-platform-packages/freedom-syncable-store-types/src/utils/__tests__/createJsonFileAtPath.test.ts
code/cross-platform-packages/freedom-syncable-store-types/src/utils/__tests__/createStringFileAtPath.test.ts
code/cross-platform-packages/freedom-syncable-store-types/src/utils/exports.ts
code/cross-platform-packages/freedom-syncable-store-types/src/utils/saltedId.ts
code/server-packages/freedom-file-system-syncable-store-backing/src/internal/consts/special-ids.ts
code/server-packages/freedom-file-system-syncable-store-backing/src/types/__tests__/FileSystemSyncableStoreBacking.test.ts

- salted IDs require a salt, which are configured when creating a SyncableStore object (can have multiple salt keys in a single store)
- without the salt, the IDs of the folders that are saltIds will be nonsense.  with the salt, they will be comprehensible

Added support for salted IDs

---

.gitignore
.idea/.gitignore
.idea/codeStyles/codeStyleConfig.xml
.idea/freedom.iml
.idea/modules.xml
.idea/runConfigurations/_template__of_NodeJsTestRunner.xml
.idea/vcs.xml
.windsurfrules
code/dev-packages/reference/README.md
code/dev-packages/reference/package.json
code/dev-packages/reference/src/exports.ts
code/dev-packages/reference/src/types/exports.ts
code/dev-packages/reference/src/utils/__tests__/demoHelper.test.ts
code/dev-packages/reference/src/utils/__tests__/demoMockingSubject.test.ts
code/dev-packages/reference/src/utils/demoHelper.ts
code/dev-packages/reference/src/utils/demoMockingSubject.ts
code/dev-packages/reference/tsconfig.base.json
code/dev-packages/reference/tsconfig.json
code/dev-packages/reference/tsconfig.mjs.json
docs/.obsidian/.gitignore
docs/.obsidian/app.json
docs/Architecture/App Structure.md
docs/Architecture/Module Structure.md
docs/Architecture/Tests.md
docs/Processes/New Module.md

@brianwestphal see these commits.
The main focus is `docs/Processes/New Module.md` - the process is always a sort of pain. So here I'm adding everything AI will need. The root file is for Windsurf, but the docs are for any agent as well as for humans.
IDE settings for WebStorm and Obsidian are only essential to make them produce compatible texts. Plus run configuration for tests.

Add IDE settings, AI&Human Guides, reference code module

---

code/cross-platform-packages/freedom-contexts/src/utils/__tests__/getEnv.test.ts
code/cross-platform-packages/freedom-contexts/src/utils/getEnv.ts

- Use devSetEnv to override an environment variable
- Use devMakeEnvDerivative to make a function that generates a new function if the environment variable changes
- Use devOnEnvChange to get a callback if an environment variable changes

DEV build mode support for overriding environment variables (primarily for web)

---

code/dev-packages/freedom-build-tools/README.md
code/dev-packages/freedom-build-tools/package.json
code/dev-packages/freedom-build-tools/src/consts/forwarded-env.ts
code/dev-packages/freedom-build-tools/src/copy-template-impl/args/Args.ts
code/dev-packages/freedom-build-tools/src/copy-template-impl/args/makeArgs.ts
code/dev-packages/freedom-build-tools/src/copy-template-impl/copyTemplate.ts
code/dev-packages/freedom-build-tools/src/copy-template-impl/index.ts
code/dev-packages/freedom-build-tools/src/copy-template-impl/runApp.ts
code/dev-packages/freedom-build-tools/src/copy-template.ts
code/dev-packages/freedom-build-tools/src/freedom-build-impl/args/Args.ts
code/dev-packages/freedom-build-tools/src/freedom-build-impl/build.ts
code/dev-packages/freedom-build-tools/src/freedom-serve-impl/args/Args.ts
code/dev-packages/freedom-build-tools/src/freedom-serve-impl/serve.ts
code/dev-packages/freedom-build-tools/src/utils/findFiles.ts

- No longer support dropping PROD: labels.  For PROD, the code should be directly functional without labels.  Dropping DEV: labels is still supported.
- Build and Serve build tools now accept '--platform' argument, which can be 'WEB' or 'NODE'
- When 'WEB', 'NODE' labels are dropped
- When 'NODE', 'WEB' labels are dropped
- Added copy-template tool which can be used to generate files from mjs scripts
- The script takes arguments:
- for files to include and, optionally, exclude (glob support)
- for prefixes to drop in the output folder (e.g. if the includes is something like 'templates/html-files/*.html', you might want to drop 'templates/' prefixes before writing to the destination directory
- the destination directory
- The default exported function from any encountered scripts (which …

Build Tools Updates

---

code/README.md
code/cross-platform-packages/freedom-async/src/internal/debugging/funcs.ts
code/cross-platform-packages/freedom-async/src/utils/callAsyncFunc.ts
code/cross-platform-packages/freedom-async/src/utils/callAsyncResultFunc.ts
code/cross-platform-packages/freedom-async/src/utils/callSyncFunc.ts
code/cross-platform-packages/freedom-async/src/utils/callSyncResultFunc.ts

- default is `all`
- can be used when FREEDOM_LOG_FUNCS doesn't select a function, to log only if there's a failure, so it's often nice to use `FREEDOM_VERBOSE_LOGGING=true FREEDOM_LOG_FUNCS=`, which will configure logging but only log failures and all function calls

Added FREEDOM_LOG_FAILURES environment variable

---

code/README.md
code/cross-platform-packages/freedom-crypto/package.json
code/cross-platform-packages/freedom-crypto/src/internal/utils/bufferFromBufferSource.ts
code/cross-platform-packages/freedom-crypto/src/internal/utils/decrypt.ts
code/cross-platform-packages/freedom-crypto/src/internal/utils/digest.ts
code/cross-platform-packages/freedom-crypto/src/internal/utils/encrypt.ts
code/cross-platform-packages/freedom-crypto/src/internal/utils/sign.ts
code/cross-platform-packages/freedom-crypto/src/internal/utils/verify.ts
code/cross-platform-packages/freedom-crypto/src/utils/decrypting/decryptBuffer.ts
code/cross-platform-packages/freedom-crypto/src/utils/encrypting/encryptBuffer.ts
code/cross-platform-packages/freedom-crypto/src/utils/signing/generateSignatureForBuffer.ts
code/cross-platform-packages/freedom-crypto/src/utils/validation/isSignatureValidForBuffer.ts

- Can be set to true (DEV build only) to replace encrypt, decrypt, sign, verify, and digest with functions that leave the content readable (but mark it so it's clear its been processed)

Added FREEDOM_MOCK_CRYPTO environment variable

---

code/cross-platform-packages/freedom-access-control/src/utils/generateSharedKeys.ts
code/cross-platform-packages/freedom-basic-data/package.json
code/cross-platform-packages/freedom-basic-data/src/consts/exports.ts
code/cross-platform-packages/freedom-basic-data/src/consts/uuid.ts
code/cross-platform-packages/freedom-basic-data/src/types/Id.ts
code/cross-platform-packages/freedom-basic-data/src/types/PrefixedString.ts
code/cross-platform-packages/freedom-basic-data/src/types/PrefixedUuid.ts
code/cross-platform-packages/freedom-basic-data/src/types/SerializedValue.ts
code/cross-platform-packages/freedom-basic-data/src/types/__tests__/SerializedValue.test.ts
code/cross-platform-packages/freedom-basic-data/src/types/exports.ts
code/cross-platform-packages/freedom-basic-data/src/utils/exports.ts
code/cross-platform-packages/freedom-basic-data/src/utils/prefixed-uuid/__tests__/makePrefixedUuidInfo.test.ts
code/cross-platform-packages/freedom-basic-data/src/utils/prefixed-uuid/exports.ts
code/cross-platform-packages/freedom-basic-data/src/utils/prefixed-uuid/makePrefixedUuidInfo.ts

- Added ZERO_UUID const for convenience
- Removed unnecessary clone step in makeIdSchema
- PrefixedString now optionally supports specifing a suffix regex
- Added PrefixedUuid
- In SerializedValue, renamed deserializedValueSchema to valueSchema

Basic Data Updates

---

code/cross-platform-packages/freedom-async/src/context/exports.ts
code/cross-platform-packages/freedom-async/src/context/probe.ts
code/cross-platform-packages/freedom-async/src/exports.ts
code/cross-platform-packages/freedom-async/src/internal/debugging/args.ts
code/cross-platform-packages/freedom-async/src/internal/debugging/funcs.ts
code/cross-platform-packages/freedom-async/src/internal/debugging/results.ts

- Use problemSettingsProvider (DEV build mode only) to enable logging, optionally including args and results, for everything inside a specified trace

Trace Probe

---

code/cross-platform-packages/freedom-syncable-store-types/package.json
code/cross-platform-packages/freedom-syncable-store-types/src/consts/timing.ts
code/cross-platform-packages/freedom-syncable-store-types/src/internal/types/DefaultMutableSyncableFolderAccessorBase.ts
code/cross-platform-packages/freedom-syncable-store-types/src/internal/types/FolderOperationsHandler.ts
code/cross-platform-packages/freedom-syncable-store-types/src/internal/types/__tests__/folders.test.ts
code/cross-platform-packages/freedom-syncable-store-types/src/internal/types/__tests__/hashes.test.ts
code/cross-platform-packages/freedom-syncable-store-types/src/types/DefaultSyncableStore.ts
code/cross-platform-packages/freedom-syncable-store-types/src/types/SyncableStore.ts
code/cross-platform-packages/freedom-syncable-store-types/src/types/__tests__/DefaultSyncableStore.test.ts
code/cross-platform-packages/freedom-syncable-store-types/src/utils/__tests__/createConflictFreeDocumentBundleAtPath.test.ts
code/cross-platform-packages/freedom-syncable-store-types/src/utils/__tests__/createJsonFileAtPath.test.ts
code/cross-platform-packages/freedom-syncable-store-types/src/utils/__tests__/createStringFileAtPath.test.ts
code/cross-platform-packages/freedom-syncable-store-types/src/utils/__tests__/getConflictFreeDocumentBundleAtPath.test.ts
code/cross-platform-packages/freedom-syncable-store-types/src/utils/get/getConflictFreeDocumentFromBundleAtPath.ts

- When watch=true on getConflictFreeDocumentFromBundleAtPath and similar now, the document is cached until 30 seconds after the last watcher calls stopWatching (and the timer is canceled if another watcher is added in the meantime)
- The watch option on getConflictFreeDocumentFromBundleAtPath and similar now supports an 'auto' value, which behaves like watch=true but then immediately stops watching
- The default value for watch is now "auto"
- SyncableStores now have a uid field, which is convenient for ensuring global caches are unique, for example
- test suites that use conflict free documents with SyncableStores should generally call `afterEach(clearDocumentCache)` since otherwise it'll wait 30 seconds to move to the next suite (since it waits for pending timeouts)

Live Documents

---

code/cross-platform-packages/freedom-email-sync/package.json
code/cross-platform-packages/freedom-email-sync/src/internal/utils/__tests__/extractNumberFromPlainSyncableId.test.ts
code/cross-platform-packages/freedom-email-sync/src/internal/utils/extractNumberFromPlainSyncableId.ts
code/cross-platform-packages/freedom-email-sync/src/utils/addMail.ts
code/cross-platform-packages/freedom-email-sync/src/utils/exports.ts
code/cross-platform-packages/freedom-email-sync/src/utils/listTimeOrganizedMailIds.ts
code/cross-platform-packages/freedom-email-sync/src/utils/makeBottomUpTimeOrganizedMailStorageTraverser.ts
code/cross-platform-packages/freedom-email-sync/src/utils/traverseTimeOrganizedMailStorageFromTheBottomUp.ts
code/cross-platform-packages/freedom-email-user/package.json
code/cross-platform-packages/freedom-email-user/src/__tests__/scenarios.test.ts
code/cross-platform-packages/freedom-email-user/src/__tests__/traverseTimeOrganizedMailStorageFromTheBottomUp.test.ts
code/freedom-email.code-workspace
code/web-worker-packages/freedom-email-tasks-web-worker/src/tasks/mail/getMailThreadsForCollection.ts

- addMail now uses the timeMSec on the StoredMail to generate the MailId
- Fixed an issue on listTimeOrganizedMailIds where numbers werent parsed properly
- Added makeBottomUpTimeOrganizedMailStorageTraverser and traverseTimeOrganizedMailStorageFromTheBottomUp to simplify mail storage traversal

Mail Storage Traversal

---

code/cross-platform-packages/freedom-object-store-types/src/types/StorableObject.ts
code/cross-platform-packages/freedom-serialization/package.json
code/cross-platform-packages/freedom-serialization/src/utils/__tests__/serialization-deserialization.test.ts
code/cross-platform-packages/freedom-serialization/src/utils/__tests__/stringify-parse.test.ts
code/cross-platform-packages/freedom-serialization/src/utils/exports.ts
code/cross-platform-packages/freedom-serialization/src/utils/parse.ts
code/cross-platform-packages/freedom-serialization/src/utils/stringify.ts
code/cross-platform-packages/freedom-syncable-store/src/utils/get/getConflictFreeDocumentFromBundleAtPath.ts
code/cross-platform-packages/freedom-task-queue/src/types/TaskQueue.ts
code/freedom-email.code-workspace
code/server-packages/freedom-json-file-object-store/README.md
code/server-packages/freedom-json-file-object-store/package.json
code/server-packages/freedom-json-file-object-store/src/exports.ts
code/server-packages/freedom-json-file-object-store/src/types/JsonFileObjectStore.ts
code/server-packages/freedom-json-file-object-store/src/types/__tests__/JsonFileObjectStore.test.ts
code/server-packages/freedom-json-file-object-store/src/types/exports.ts
code/server-packages/freedom-json-file-object-store/tsconfig.base.json
code/server-packages/freedom-json-file-object-store/tsconfig.json
code/server-packages/freedom-json-file-object-store/tsconfig.mjs.json

- A new ObjectStore implementation for persisting to JSON files, for testing purposes mostly
- This reads from a JSON file (which may or may not initially exist) and eventually persists changes back into that JSON file
Other semi-related changes:
- Added parse and stringify methods to freedom-serialization
- Added makeStorableObjectSchema helper (to go along with StorableObject)
- Fixed an issue with TaskQueue and dealing with multiple tasks for the same key when one is in flight

Added freedom-json-file-object-store

---

.obsidian/.gitignore
.obsidian/app.json

I opened Obsidian on the root instead of docs which I think might be common? If so, I'm thinking we should copy the .obsidian config folder also into the root.

add .obsidian folder to root

---

code/apps/freedom-email-app/package.json
code/apps/freedom-email-app/src/modules/mail-collection/components/MailThreadListItem.tsx
code/apps/freedom-email-app/src/modules/mail-thread/components/MailListItem.tsx
code/yarn.lock

- On the summary list, it now wraps when there's multiple from names or a long name and ellipsizes when it's too wide
- On the detail list, it now wraps and ellipsizes names and wraps email addresses anywhere if needed
- From groups are now better supported as well
Still, all of this should be considered placeholder UI until we have a more comprehensive app design.
https://github.com/freedom-tech-hq/main/issues/66

Fixed email from field more generally

---

code/cross-platform-packages/freedom-async/src/config/logging.ts

@brianwestphal Please check.
I still don't understand how this part works (still forgetting that `DEV:` requires its own build env var). But this fix seems obvious.

Explain devOnEnvChange('FREEDOM_VERBOSE_LOGGING')

---

code/backends/freedom-mail-host/src/main.ts
code/backends/freedom-store-api-server/src/main.ts
code/cross-platform-packages/freedom-contexts/src/internal/utils/makeStructuredLog.ts
code/cross-platform-packages/freedom-contexts/src/types/LoggingMode.ts
code/cross-platform-packages/freedom-contexts/src/utils/wrapLoggingFunc.ts

One concern: I've caught two eslint false-positives. Not addressing them now.
Decided not to use `chalk` - the scope of color codes is limited and they have not changed for decades. A comment is enough for readability.

Implement log mode that would be readable in docker logs

---

code/cross-platform-packages/freedom-email-user/package.json
code/cross-platform-packages/freedom-email-user/src/__tests__/listTimeOrganizedMailIds.test.ts
code/cross-platform-packages/freedom-email-user/src/__tests__/scenarios.test.ts
code/cross-platform-packages/freedom-email-user/src/__tests__/traverseTimeOrganizedMailStorageFromTheBottomUp.test.ts
code/cross-platform-packages/freedom-in-memory-cache/src/classes/InMemoryCache.ts
code/cross-platform-packages/freedom-in-memory-cache/src/classes/__tests__/InMemoryCache.test.ts
code/cross-platform-packages/freedom-syncable-store/src/internal/types/__tests__/folders.test.ts
code/cross-platform-packages/freedom-syncable-store/src/internal/types/__tests__/hashes.test.ts
code/cross-platform-packages/freedom-syncable-store/src/types/__tests__/DefaultSyncableStore.test.ts
code/cross-platform-packages/freedom-syncable-store/src/utils/__tests__/createConflictFreeDocumentBundleAtPath.test.ts
code/cross-platform-packages/freedom-syncable-store/src/utils/__tests__/createJsonFileAtPath.test.ts
code/cross-platform-packages/freedom-syncable-store/src/utils/__tests__/createStringFileAtPath.test.ts
code/cross-platform-packages/freedom-syncable-store/src/utils/__tests__/getConflictFreeDocumentBundleAtPath.test.ts
code/server-packages/freedom-file-system-syncable-store-backing/package.json
code/server-packages/freedom-file-system-syncable-store-backing/src/types/__tests__/FileSystemSyncableStoreBacking.test.ts

- invalidateAllInMemoryCaches is replacing clearDocumentCache soon, but for now, doing both in some places
- tracking which InMemoryCache instances are non-empty so we can easily access the list and invalidate everything without having a memory leak

Added invalidateAllInMemoryCaches to all test suites that needed it

---

code/backends/freedom-mail-host/package.json
code/cross-platform-packages/freedom-access-control-types/src/types/AccessControlDocument.ts
code/cross-platform-packages/freedom-access-control/src/__test_dependency__/TestAccessControlDocument.ts
code/cross-platform-packages/freedom-access-control/src/utils/__tests__/generateSignedAddAccessChange.test.ts
code/cross-platform-packages/freedom-access-control/src/utils/__tests__/generateSignedModifyAccessChange.test.ts
code/cross-platform-packages/freedom-access-control/src/utils/generateSignedModifyAccessChange.ts
code/cross-platform-packages/freedom-async/src/classes/AsyncTransient.ts
code/cross-platform-packages/freedom-async/src/classes/__tests__/AsyncTransient.test.ts
code/cross-platform-packages/freedom-async/src/classes/exports.ts
code/cross-platform-packages/freedom-async/src/exports.ts
code/cross-platform-packages/freedom-conflict-free-document/package.json
code/cross-platform-packages/freedom-conflict-free-document/src/types/ConflictFreeDocument.ts
code/cross-platform-packages/freedom-conflict-free-document/src/types/__test_dependency__/ConflictFreeTestDocument.ts
code/cross-platform-packages/freedom-conflict-free-document/src/types/__tests__/ConflictFreeDocument.test.ts
code/cross-platform-packages/freedom-email-user/src/types/MailCollectionMetaDocument.ts
code/cross-platform-packages/freedom-email-user/src/types/MailDraftDocument.ts
code/cross-platform-packages/freedom-syncable-store-types/src/types/ISyncableStoreAccessControlDocument.ts
code/cross-platform-packages/freedom-syncable-store/src/internal/types/DefaultMutableSyncableFolderAccessorBase.ts
code/cross-platform-packages/freedom-syncable-store/src/internal/types/FolderOperationsHandler.ts
code/cross-platform-packages/freedom-syncable-store/src/types/SyncableStoreAccessControlDocument.ts
code/cross-platform-packages/freedom-syncable-store/src/types/SyncableStoreChangesDocument.ts
code/cross-platform-packages/freedom-syncable-store/src/utils/create/createConflictFreeDocumentBundleAtPath.ts
code/cross-platform-packages/freedom-syncable-store/src/utils/get/getConflictFreeDocumentFromBundleAtPath.ts
code/cross-platform-packages/freedom-syncable-store/src/utils/validation/getRoleForOrigin.ts
code/server-packages/freedom-db/package.json
code/server-packages/freedom-email-server/package.json
code/server-packages/freedom-syncable-store-server/package.json

- AccessControlDocument now uses async crdt fields for initialState_, initialPublicKeysById_, and changes_
- Added AsyncTransient class for computing async cached data (for a single "field" that might need to be invalidated semi-frequently)
- Other document changes to support async

Async Docs

---

code/cross-platform-packages/freedom-email-sync/src/utils/addMail.ts
code/cross-platform-packages/freedom-email-user/src/utils/addMailDraft.ts
code/cross-platform-packages/freedom-email-user/src/utils/addMailToOutbox.ts
code/cross-platform-packages/freedom-email-user/src/utils/createDefaultCollectionsForUser.ts
code/cross-platform-packages/freedom-email-user/src/utils/createInitialSyncableStoreStructureForUser.ts
code/cross-platform-packages/freedom-syncable-store/src/utils/get-or-create/getOrCreateBundleAtPath.ts
code/cross-platform-packages/freedom-syncable-store/src/utils/get-or-create/getOrCreateBundlesAtPaths.ts
code/web-worker-packages/freedom-email-tasks-web-worker/src/internal/utils/createMailIdMarkerFile.ts

- These names are encrypted, but can be useful both for debugging and if an end-user were to ever try to "browse" their files (with future tools)

Added Names to Files

---

code/cross-platform-packages/freedom-locking-types/src/types/InMemoryLockStore.ts
code/cross-platform-packages/freedom-locking-types/src/types/Lock.ts
code/cross-platform-packages/freedom-locking-types/src/types/acquired-locks.ts
code/cross-platform-packages/freedom-locking-types/src/types/exports.ts
code/cross-platform-packages/freedom-locking-types/src/utils/__tests__/withAcquiredLock.test.ts
code/cross-platform-packages/freedom-locking-types/src/utils/withAcquiredLock.ts

- If the same lock is used in a nested fashion with withAcquiredLock, it will automatically be allowed and not try to acquire (and deadlock)
- useAcquiredLocks is now available as a trace hook -- it allows one to look up the uids of acquired locks within a trace

Nested Locks

---

code/cross-platform-packages/freedom-sync-service/src/utils/makeSyncService.ts
code/cross-platform-packages/freedom-syncable-store/src/utils/get/getConflictFreeDocumentFromBundleAtPath.ts
code/cross-platform-packages/freedom-syncable-store/src/utils/getRecursiveFolderPaths.ts
code/cross-platform-packages/freedom-task-queue/package.json
code/cross-platform-packages/freedom-task-queue/src/types/TaskQueue.ts
code/cross-platform-packages/freedom-task-queue/src/types/__tests__/TaskQueue.test.ts
code/server-packages/freedom-json-file-object-store/src/types/JsonFileObjectStore.ts
code/web-worker-packages/freedom-email-tasks-web-worker/src/internal/tasks/mail/routeMail.ts

- TaskQueues now have ids
- In DEV build mode, TaskQueues that have active, pending, or recently completed items now generate a report (to the debug logger) every 10 seconds
- Now support priority flag.  'high' prepends whereas 'default' appends

Task Queue Updates

---

code/apps/freedom-email-app/project.json
code/nx.json

- NX now rebuilds if FREEDOM_BUILD_MODE changes
- it only rebuilds most packages if the resulting interface (.d.ts) of dependencies change (or if any bin/ or build/ files change)
- freedom-email-app is a bundled build however, so it needs to build anytime anything changes like before, so it has a project.json file to override things

Improved NX Config

---

code/cross-platform-packages/freedom-task-queue/src/types/TaskQueue.ts
code/cross-platform-packages/freedom-task-queue/src/types/__tests__/TaskQueue.test.ts
code/yarn.lock

- Now supports pausing (which can be called repeatedly and only resumes once all pending unpauses are called)

Updated Task Queue

---

code/apps/freedom-email-app/src/modules/mail-collection/hooks/useMailCollectionDataSource.ts
code/apps/freedom-email-app/src/modules/mail-collections-list/hooks/useMailCollectionsListDataSource.ts
code/apps/freedom-email-app/src/modules/mail-thread/hooks/useMailThreadDataSource.ts
code/backends/freedom-mail-host/package.json
code/backends/freedom-mail-host/src/config.ts
code/backends/freedom-mail-host/src/modules/smtp-server/actions/onValidateReceiver.ts
code/backends/freedom-mail-host/src/modules/smtp-server/internal/utils/__tests__/defineSmtpServer.test.ts
code/backends/freedom-mail-host/src/modules/syncable-store/utils/routeMail.ts
code/backends/freedom-store-api-server/src/config.ts
code/cross-platform-packages/freedom-contexts/src/utils/wrapLoggingFunc.ts
code/dev-packages/freedom-dev-scripts/src/package-sync/utils/findPackages.ts
code/dev-packages/freedom-dev-scripts/src/package-sync/utils/utils.ts
code/eslint.config.mjs
code/server-packages/freedom-config/README.md
code/server-packages/freedom-config/src/utils/__tests__/from.test.ts
code/server-packages/freedom-config/src/utils/from.ts
code/server-packages/freedom-config/src/utils/loadEnv.ts
code/server-packages/freedom-email-server/src/utils/subscribeOnOutboundEmails.ts

- Lint rules are now more strict about use of curly braces
- Also more strict about implicit boolean expressions
- Updated code as appropriate
- Updated freedom-config to be more type safe wrt asCustom
- Replaced asCustom extension with getAsCustom and getRequiredAsCustom to avoid type erasure from generic function passed as extension

Updated Lint Rules and Updated freedom-config

---

code/server-packages/freedom-config/src/utils/defineConfig.ts
code/server-packages/freedom-config/src/utils/exports.ts
code/server-packages/freedom-config/src/utils/from.ts
code/server-packages/freedom-config/src/utils/getFileEnvVar.ts
code/server-packages/freedom-config/src/utils/getJsonFileEnvVar.ts

@brianwestphal FYI. This was implemented before your refactoring on env-var extensions. I will unify the patterns later in an iteration on the config.

Implement getFileEnvVar, getJsonFileEnvVar in freedom-config

---

code/backends/freedom-mail-host/package.json
code/cross-platform-packages/freedom-syncable-store/src/internal/types/DefaultFileStore.ts
code/cross-platform-packages/freedom-syncable-store/src/internal/types/DefaultFolderStore.ts
code/cross-platform-packages/freedom-syncable-store/src/internal/types/DefaultMutableSyncableItemAccessorBase.ts
code/server-packages/freedom-config/package.json
code/server-packages/freedom-db/package.json
code/server-packages/freedom-email-server/package.json
code/server-packages/freedom-redlock-store/package.json

- We were clearing the metadata for the item and its ancestors on creation, when we were already computing the items metadata (especially for binary files).  Should have only invalidated the ancestors' metadata

Fixed Redundant Metadata Computation on Item Creation
